import { z } from 'zod'
import {
  AppMentionSchema,
  NotificationChannelSchema,
  VerificationProfileSchema,
  WorkflowSchema,
} from '../../config/schema.js'
import type { SettingDefinition } from '../registry.js'
import {
  booleanSetting,
  jsonSetting,
  numberSetting,
  stringSetting,
  validateJsonSettingShape,
} from '../registry.js'

const GithubAppMentionsOverrideSchema = z.record(AppMentionSchema)
const NotificationsChannelsOverrideSchema = z.array(NotificationChannelSchema)
const WorkflowsOverrideSchema = z.record(WorkflowSchema)
const VerificationProfilesOverrideSchema = z.record(VerificationProfileSchema)

export function githubDefinitions(): SettingDefinition[] {
  return [
    stringSetting({
      key: 'github.tokenEnv',
      label: 'GitHub Token Env Var',
      description: 'Environment variable name used for GitHub authentication.',
      details: 'Set the env var name that stores the GitHub token. This must be a variable name, not a literal token value.',
      defaultValue: null,
      yamlPath: ['github', 'tokenEnv'],
      minLength: 1,
      validate: (value) => {
        if (value.startsWith('ghp_') || value.startsWith('ghs_') || value.startsWith('github_pat_')) {
          return 'github.tokenEnv should be an environment variable name, not a literal token'
        }
        return null
      },
    }),
    stringSetting({
      key: 'github.apiBaseUrl',
      label: 'GitHub API Base URL',
      description: 'Base URL for GitHub API requests.',
      details: 'Override the API base URL used for GitHub repos. Useful for GitHub Enterprise deployments.',
      defaultValue: 'https://api.github.com',
      yamlPath: ['github', 'apiBaseUrl'],
      minLength: 1,
      url: true,
    }),
    numberSetting({
      key: 'github.pollIntervalSeconds',
      label: 'Poll Interval (seconds)',
      description: 'Delay between automatic poll cycles.',
      details: 'Controls how often night-orch checks configured repos for work. Lower values react faster but increase API traffic.',
      defaultValue: 300,
      yamlPath: ['github', 'pollIntervalSeconds'],
      integer: true,
      min: 5,
      max: 3600,
      step: 5,
    }),
    jsonSetting({
      key: 'github.appMentions',
      label: 'GitHub App Mentions',
      description: 'Mention template map used for app-trigger comments.',
      details: 'Record keyed by mention alias with enabled flag and comment template payloads.',
      defaultValue: {},
      yamlPath: ['github', 'appMentions'],
      normalize: (value) => validateJsonSettingShape(value, GithubAppMentionsOverrideSchema, 'github.appMentions'),
    }),

    stringSetting({
      key: 'storage.dbPath',
      label: 'State DB Path',
      description: 'SQLite database file path.',
      details: 'Location of the runtime state database file. Read-only at runtime because DB opens before overrides are loaded.',
      defaultValue: '~/.config/night-orch/state.db',
      yamlPath: ['storage', 'dbPath'],
      minLength: 1,
      mutable: false,
    }),
    stringSetting({
      key: 'storage.worktreeRoot',
      label: 'Worktree Root',
      description: 'Root directory used for issue worktrees.',
      details: 'Base path where dedicated issue worktrees are created.',
      defaultValue: '~/code/.night-orch/worktrees',
      yamlPath: ['storage', 'worktreeRoot'],
      minLength: 1,
    }),
    stringSetting({
      key: 'storage.logsRoot',
      label: 'Logs Root',
      description: 'Root directory used for run/session logs.',
      details: 'Base path where runtime log files are written.',
      defaultValue: '~/code/.night-orch/logs',
      yamlPath: ['storage', 'logsRoot'],
      minLength: 1,
    }),
    booleanSetting({
      key: 'storage.autoCleanup.enabled',
      label: 'Auto Cleanup Enabled',
      description: 'Enable periodic cleanup jobs.',
      details: 'When enabled, stale worktrees and old logs are cleaned up automatically on schedule.',
      defaultValue: true,
      yamlPath: ['storage', 'autoCleanup', 'enabled'],
    }),
    numberSetting({
      key: 'storage.autoCleanup.intervalMinutes',
      label: 'Auto Cleanup Interval (minutes)',
      description: 'How often automatic cleanup runs.',
      details: 'Interval between automatic cleanup runs.',
      defaultValue: 60,
      yamlPath: ['storage', 'autoCleanup', 'intervalMinutes'],
      integer: true,
      min: 1,
      step: 5,
    }),
    numberSetting({
      key: 'storage.retention.worktreeAgeDays',
      label: 'Worktree Retention (days)',
      description: 'Retention window for stale worktrees.',
      details: 'Completed/error worktrees older than this threshold may be removed during cleanup.',
      defaultValue: 7,
      yamlPath: ['storage', 'retention', 'worktreeAgeDays'],
      integer: true,
      min: 1,
      step: 1,
    }),
    numberSetting({
      key: 'storage.retention.detailDays',
      label: 'Detail Retention (days)',
      description: 'Retention window for detailed run data.',
      details: 'Detailed run artifacts are retained for this many days before archival/cleanup.',
      defaultValue: 30,
      yamlPath: ['storage', 'retention', 'detailDays'],
      integer: true,
      min: 1,
      step: 1,
    }),
    numberSetting({
      key: 'storage.retention.archiveDays',
      label: 'Archive Retention (days)',
      description: 'Retention window for archived run data.',
      details: 'Archived records older than this threshold can be removed.',
      defaultValue: 90,
      yamlPath: ['storage', 'retention', 'archiveDays'],
      integer: true,
      min: 1,
      step: 1,
    }),

    jsonSetting({
      key: 'notifications.channels',
      label: 'Notification Channels',
      description: 'Configured notification channel list.',
      details: 'Array of notification channel definitions (console/webhook/discord/smtp).',
      defaultValue: [{ type: 'console' }],
      yamlPath: ['notifications', 'channels'],
      normalize: (value) => validateJsonSettingShape(value, NotificationsChannelsOverrideSchema, 'notifications.channels'),
    }),

    booleanSetting({
      key: 'notifications.events.onRunStarted',
      label: 'Notify: Run Started',
      description: 'Send notifications when runs start.',
      details: 'Controls whether run-started notifications are dispatched.',
      defaultValue: false,
      yamlPath: ['notifications', 'events', 'onRunStarted'],
    }),
    booleanSetting({
      key: 'notifications.events.onBlocked',
      label: 'Notify: Blocked',
      description: 'Send notifications when runs become blocked.',
      details: 'Controls whether blocked-run notifications are dispatched.',
      defaultValue: true,
      yamlPath: ['notifications', 'events', 'onBlocked'],
    }),
    booleanSetting({
      key: 'notifications.events.onPrReady',
      label: 'Notify: PR Ready',
      description: 'Send notifications when PRs are ready.',
      details: 'Controls whether ready-for-review PR notifications are dispatched.',
      defaultValue: true,
      yamlPath: ['notifications', 'events', 'onPrReady'],
    }),
    booleanSetting({
      key: 'notifications.events.onPrUpdated',
      label: 'Notify: PR Updated',
      description: 'Send notifications when PRs are updated.',
      details: 'Controls whether PR update notifications are dispatched.',
      defaultValue: true,
      yamlPath: ['notifications', 'events', 'onPrUpdated'],
    }),
    booleanSetting({
      key: 'notifications.events.onError',
      label: 'Notify: Error',
      description: 'Send notifications on orchestration errors.',
      details: 'Controls whether error notifications are dispatched.',
      defaultValue: true,
      yamlPath: ['notifications', 'events', 'onError'],
    }),
    booleanSetting({
      key: 'notifications.events.onRetryExhausted',
      label: 'Notify: Retry Exhausted',
      description: 'Send notifications when retries are exhausted.',
      details: 'Controls whether retry-exhausted notifications are dispatched.',
      defaultValue: true,
      yamlPath: ['notifications', 'events', 'onRetryExhausted'],
    }),

    booleanSetting({
      key: 'mcp.enabled',
      label: 'MCP Enabled',
      description: 'Enable MCP server exposure.',
      details: 'Turns MCP server availability on or off for applicable commands/modes.',
      defaultValue: false,
      yamlPath: ['mcp', 'enabled'],
    }),
    stringSetting({
      key: 'mcp.transport',
      label: 'MCP Transport',
      description: 'Transport protocol used by MCP server.',
      details: 'Currently only stdio transport is supported.',
      defaultValue: 'stdio',
      yamlPath: ['mcp', 'transport'],
      options: ['stdio'],
    }),
    stringSetting({
      key: 'mcp.authTokenEnv',
      label: 'MCP Auth Token Env Var',
      description: 'Optional env var name containing MCP mutation auth token.',
      details: 'Set to null (or clear in YAML) to disable MCP mutation token checks.',
      defaultValue: null,
      yamlPath: ['mcp', 'authTokenEnv'],
      allowNull: true,
      minLength: 1,
    }),
    numberSetting({
      key: 'mcp.httpPort',
      label: 'MCP HTTP Port',
      description: 'TCP port for embedded MCP HTTP transport.',
      details: 'Port used when running embedded MCP HTTP/SSE mode.',
      defaultValue: 3100,
      yamlPath: ['mcp', 'httpPort'],
      integer: true,
      min: 1,
      max: 65535,
      step: 1,
    }),
    stringSetting({
      key: 'mcp.httpHost',
      label: 'MCP HTTP Host',
      description: 'Bind address for embedded MCP HTTP transport.',
      details: 'Network interface/address used for MCP HTTP endpoint binding.',
      defaultValue: '127.0.0.1',
      yamlPath: ['mcp', 'httpHost'],
      minLength: 1,
    }),

    booleanSetting({
      key: 'commentCommands.enabled',
      label: 'Comment Commands Enabled',
      description: 'Enable issue comment command processing.',
      details: 'If enabled, `/orch` comment commands are parsed and processed.',
      defaultValue: true,
      yamlPath: ['commentCommands', 'enabled'],
    }),
    booleanSetting({
      key: 'commentCommands.requireCollaborator',
      label: 'Require Collaborator For Commands',
      description: 'Require collaborator permission for comment commands.',
      details: 'When enabled, only collaborators can run issue comment commands.',
      defaultValue: true,
      yamlPath: ['commentCommands', 'requireCollaborator'],
    }),
    jsonSetting({
      key: 'workflows',
      label: 'Workflow Definitions',
      description: 'Named workflow definitions.',
      details: 'Record of named workflow graphs (steps/roles/agents) used by workflow selection.',
      defaultValue: {},
      yamlPath: ['workflows'],
      normalize: (value) => validateJsonSettingShape(value, WorkflowsOverrideSchema, 'workflows'),
    }),
    jsonSetting({
      key: 'verificationProfiles',
      label: 'Verification Profiles',
      description: 'Named staged verification profiles.',
      details: 'Record of staged verify definitions used by repos/workflows to run smoke/full/nightly command sets.',
      defaultValue: {},
      yamlPath: ['verificationProfiles'],
      normalize: (value) => validateJsonSettingShape(value, VerificationProfilesOverrideSchema, 'verificationProfiles'),
    }),
  ]
}
