import type { SettingDefinition } from '../registry.js'
import { booleanSetting, numberSetting, stringSetting } from '../registry.js'

export function loopDefinitions(): SettingDefinition[] {
  return [
    numberSetting({
      key: 'loop.maxReviewIterations',
      label: 'Max Review Iterations',
      description: 'Maximum review correction loops per run.',
      details: 'Limits how many review-fix-review cycles a run can execute before stopping.',
      defaultValue: 4,
      yamlPath: ['loop', 'maxReviewIterations'],
      integer: true,
      min: 1,
      step: 1,
    }),
    numberSetting({
      key: 'loop.maxTotalAgentPasses',
      label: 'Max Total Agent Passes',
      description: 'Hard cap on planner/coder/reviewer passes in one run.',
      details: 'Caps total planner/coder/reviewer passes across the full run.',
      defaultValue: 10,
      yamlPath: ['loop', 'maxTotalAgentPasses'],
      integer: true,
      min: 1,
      step: 1,
    }),
    numberSetting({
      key: 'loop.maxAttemptChainLength',
      label: 'Max Attempt Chain Length',
      description: 'Hard cap on follow-up attempts for a single issue chain.',
      details: 'When reached, retry/continue/rebase follow-ups are rejected and the issue stays blocked for human intervention.',
      defaultValue: 3,
      yamlPath: ['loop', 'maxAttemptChainLength'],
      integer: true,
      min: 1,
      max: 20,
      step: 1,
    }),
    numberSetting({
      key: 'loop.maxRunTokens',
      label: 'Max Run Tokens',
      description: 'Optional token budget for a single attempt.',
      details: 'When set, the loop blocks once cumulative prompt+completion+cache tokens for this run reach the cap.',
      defaultValue: 0,
      yamlPath: ['loop', 'maxRunTokens'],
      integer: true,
      min: 0,
      step: 1,
    }),
    numberSetting({
      key: 'loop.maxIssueTokens',
      label: 'Max Issue Tokens',
      description: 'Optional cumulative token budget across all attempts for one issue.',
      details: 'When set, retries/continues stop once total tokens for the issue chain reach the cap.',
      defaultValue: 0,
      yamlPath: ['loop', 'maxIssueTokens'],
      integer: true,
      min: 0,
      step: 1,
    }),
    numberSetting({
      key: 'loop.maxDailyTokens',
      label: 'Max Daily Tokens',
      description: 'Optional UTC-day token budget across all runs.',
      details: 'When set, new work blocks once today\'s cumulative tokens reach the cap.',
      defaultValue: 0,
      yamlPath: ['loop', 'maxDailyTokens'],
      integer: true,
      min: 0,
      step: 1,
    }),
    numberSetting({
      key: 'loop.maxRunWallClockMinutes',
      label: 'Max Run Wall-Clock Minutes',
      description: 'Optional elapsed-time cap for a single run.',
      details: 'When set, the loop blocks once wall-clock time since run start reaches this limit.',
      defaultValue: 0,
      yamlPath: ['loop', 'maxRunWallClockMinutes'],
      integer: false,
      min: 0,
      step: 0.1,
    }),
    booleanSetting({
      key: 'loop.stopOnPlannerFailure',
      label: 'Stop On Planner Failure',
      description: 'Stop run when planner output fails validation.',
      details: 'If enabled, planner failure ends the run early instead of proceeding.',
      defaultValue: true,
      yamlPath: ['loop', 'stopOnPlannerFailure'],
    }),
    booleanSetting({
      key: 'loop.requireVerificationPass',
      label: 'Require Verification Pass',
      description: 'Require verify commands to pass before completion.',
      details: 'If enabled, failed verification blocks completion.',
      defaultValue: true,
      yamlPath: ['loop', 'requireVerificationPass'],
    }),
    stringSetting({
      key: 'loop.reviewApprovalKeyword',
      label: 'Review Approval Keyword',
      description: 'Reviewer keyword interpreted as approval.',
      details: 'Expected keyword emitted by reviewer agent for approval.',
      defaultValue: 'APPROVED',
      yamlPath: ['loop', 'reviewApprovalKeyword'],
      minLength: 1,
    }),
    stringSetting({
      key: 'loop.reviewNeedsChangesKeyword',
      label: 'Review Needs-Changes Keyword',
      description: 'Reviewer keyword interpreted as changes required.',
      details: 'Expected keyword emitted by reviewer agent for change requests.',
      defaultValue: 'CHANGES_REQUIRED',
      yamlPath: ['loop', 'reviewNeedsChangesKeyword'],
      minLength: 1,
    }),
    booleanSetting({
      key: 'loop.blockOnAmbiguousReview',
      label: 'Block On Ambiguous Review',
      description: 'Block run if review output is ambiguous.',
      details: 'If enabled, unparseable reviewer output results in blocked status.',
      defaultValue: true,
      yamlPath: ['loop', 'blockOnAmbiguousReview'],
    }),
    numberSetting({
      key: 'loop.maxAutoRetries',
      label: 'Max Auto Retries',
      description: 'Automatic retry attempts for infrastructure failures.',
      details: 'Maximum number of automatic retries after transient failures.',
      defaultValue: 3,
      yamlPath: ['loop', 'maxAutoRetries'],
      integer: true,
      min: 0,
      step: 1,
    }),
    numberSetting({
      key: 'loop.maxEmptyDiffRetries',
      label: 'Max Empty-Diff Retries',
      description: 'Auto-retry count when coder produces no file changes.',
      details: 'When the coder finishes a pass with zero file changes and the reviewer has nothing to flag, decide() iterates back to the coder up to this many times before blocking the attempt.',
      defaultValue: 2,
      yamlPath: ['loop', 'maxEmptyDiffRetries'],
      integer: true,
      min: 0,
      max: 5,
      step: 1,
    }),
    numberSetting({
      key: 'loop.maxConsecutiveBlocks',
      label: 'Max Consecutive Blocks',
      description: 'Circuit breaker for repeated blocks on the same issue.',
      details: 'If an issue accumulates this many consecutive blocked attempts without a successful run in between, the poller skips it on future cycles until the block label is manually cleared. Prevents runaway loops.',
      defaultValue: 4,
      yamlPath: ['loop', 'maxConsecutiveBlocks'],
      integer: true,
      min: 1,
      max: 20,
      step: 1,
    }),
    booleanSetting({
      key: 'loop.decompose',
      label: 'Enable Decomposition',
      description: 'Allow issue decomposition into sub-tasks.',
      details: 'If enabled, eligible issues can be split into dependent sub-tasks.',
      defaultValue: false,
      yamlPath: ['loop', 'decompose'],
    }),
    numberSetting({
      key: 'loop.maxSubtasks',
      label: 'Max Subtasks',
      description: 'Maximum sub-tasks per decomposition.',
      details: 'Upper bound for generated decomposition sub-tasks.',
      defaultValue: 5,
      yamlPath: ['loop', 'maxSubtasks'],
      integer: true,
      min: 1,
      max: 10,
      step: 1,
    }),
    numberSetting({
      key: 'loop.maxConcurrentSubtasks',
      label: 'Max Concurrent Subtasks',
      description: 'Maximum parallel sub-task executions.',
      details: 'Upper bound for concurrently running sub-task worktrees.',
      defaultValue: 3,
      yamlPath: ['loop', 'maxConcurrentSubtasks'],
      integer: true,
      min: 1,
      max: 10,
      step: 1,
    }),
  ]
}
